<?xml version="1.0" encoding="utf-8"?>
<ThermalLabel Version="10.0" Width="4" Height="2" GapLength="0" MarkLength="0" OffsetLength="0" UnitType="Inch" LabelsPerRow="2" LabelsHorizontalGapLength="0.188" IsContinuous="False" PrintSpeed="" PrintMirror="False" CutAfterPrinting="False" SheetLabelsWidth="8.5" SheetLabelsHeight="11" SheetLabelsCount="10" SheetLabelsMargin="0.156,0.5,0,0">
  <Items>
    <BarcodeItem X="0.2135" Y="0.9896" DataField="id" Width="3.5833" Height="0.8854" Symbology="Code128" Code="_x0031_23456789" AddChecksum="False" BarcodeAlignment="MiddleCenter" Font="NativePrinterFontA,5,Point,,,False,90,,CP850" Sizing="FitProportional" TextFont="NativePrinterFontA,10,Point,,,False,90,,CP850" MaxiCodeDrawPixelBasedSymbol="True" DotCodeAspectRatio="" />
    <TextItem X="0.2136" Y="0.0834" DataField="title" Width="3.6459" Height="0.2812" Text="Type_x0020_here" Font="ZPL Font 0,12,Point,,,False,90,,CP850" />
    <TextItem X="0.2032" Y="0.4584" DataField="author" Width="3.6459" Height="0.2812" Text="Type_x0020_here" Font="ZPL Font 0,12,Point,,,False,90,,CP850" />
  </Items>
</ThermalLabel>