<?xml version="1.0" encoding="utf-8"?>
<ThermalLabel Version="9.0" Width="2.5" Height="4.5625" GapLength="0" MarkLength="0" OffsetLength="0" UnitType="Inch" LabelsPerRow="1" LabelsHorizontalGapLength="0" IsContinuous="False" PrintSpeed="" PrintMirror="False" CutAfterPrinting="False">
  <Items>
    <RectangleShapeItem Width="2.5" Height="4.5625" />
    <TextItem X="0.0312" Y="0.0312" Width="2.4375" Height="0.3438" Text="Nutrition_x0020_Facts" Font="Arial,24,True,False,False,False,Point,,,False,90,,CP850" />
    <LineShapeItem X="0.0312" Y="0.37" Width="2.4375" Height="0.01" />
    <TextItem X="0.0312" Y="0.4062" Width="2.4375" Height="0.1875" Text="_x0030__x0020_servings_x0020_per_x0020_container" Font="Arial,10,Point,,,False,90,,CP850" />
    <TextItem X="0.0312" Y="0.5938" Width="1.2188" Height="0.1875" Text="Serving_x0020_size" Font="Arial,10,True,False,False,False,Point,,,False,90,,CP850" />
    <TextItem X="1.25" Y="0.5938" Width="1.2188" Height="0.1875" Text="_x0030__x0020_cup_x0020__x0028_000g_x0029_" Font="Arial,10,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="0.7938" Width="2.4375" Height="0.1" StrokeThickness="0.1" />
    <TextItem X="0.0312" Y="0.9062" Width="2.4375" Height="0.125" Text="Amount_x0020_per_x0020_serving" Font="Arial,6,True,False,False,False,Point,,,False,90,,CP850" />
    <TextItem X="0.0312" Y="1" Width="1.2188" Height="0.2188" Text="Calories" Font="Arial,16,True,False,False,False,Point,,,False,90,,CP850" />
    <TextItem X="1.25" Y="0.9062" Width="1.2188" Height="0.3125" Text="_x0030_00" Font="Arial,22,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="1.229" Width="2.4375" Height="0.042" StrokeThickness="0.042" />
    <LineShapeItem X="0.0312" Y="1.4013" Width="2.4375" Height="0.01" />
    <TextItem X="1.25" Y="1.2912" Width="1.2188" Height="0.125" Text="_x0025__x0020_Daily_x0020_Value_x0020__x002A_" Font="Arial,6,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="1.5888" Width="2.4375" Height="0.01" />
    <TextItem X="0.0312" Y="1.4375" Width="1.8438" Height="0.1562" Text="_x005B_b_x005D_Total_x0020_Fat_x005B__x002F_b_x005D__x0020_0g" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="1.4375" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="1.7762" Width="2.4375" Height="0.01" />
    <TextItem X="0.1562" Y="1.625" Width="1.7188" Height="0.1562" Text="Saturated_x0020_Fat_x0020_0g" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="1.625" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="1.9638" Width="2.4375" Height="0.01" />
    <TextItem X="0.1562" Y="1.8125" Width="1.7188" Height="0.1562" Text="_x005B_i_x005D_Trans_x005B__x002F_i_x005D__x0020_Fat_x0020_0g" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="1.8125" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="2.1512" Width="2.4375" Height="0.01" />
    <TextItem X="0.0312" Y="2" Width="1.8438" Height="0.1562" Text="_x005B_b_x005D_Choresterol_x005B__x002F_b_x005D__x0020_0mg" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="2" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="2.3388" Width="2.4375" Height="0.01" />
    <TextItem X="0.0312" Y="2.1875" Width="1.8438" Height="0.1562" Text="_x005B_b_x005D_Sodium_x005B__x002F_b_x005D__x0020_0mg" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="2.1875" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="2.5262" Width="2.4375" Height="0.01" />
    <TextItem X="0.0312" Y="2.375" Width="1.8438" Height="0.1562" Text="_x005B_b_x005D_Total_x0020_Carbohydrate_x005B__x002F_b_x005D__x0020_0g" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="2.375" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="2.7137" Width="2.4375" Height="0.01" />
    <TextItem X="0.1562" Y="2.5625" Width="1.7188" Height="0.1562" Text="Dietary_x0020_Fiber_x0020_0g" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="2.5625" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.2812" Y="2.9012" Width="2.1875" Height="0.01" />
    <TextItem X="0.1562" Y="2.75" Width="1.7188" Height="0.1562" Text="Total_x0020_Sugars_x0020_0g" Font="Arial,8,Point,,,False,90,,CP850" />
    <LineShapeItem X="0.0312" Y="3.0887" Width="2.4375" Height="0.01" />
    <TextItem X="0.2812" Y="2.9375" Width="1.5938" Height="0.1562" Text="Includes_x0020_0g_x0020_Added_x0020_Sugars" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="2.9375" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="3.2762" Width="2.4375" Height="0.1" StrokeThickness="0.1" />
    <TextItem X="0.0312" Y="3.125" Width="1.8438" Height="0.1562" Text="_x005B_b_x005D_Protein_x005B__x002F_b_x005D__x0020_0g" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="3.125" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="3.5888" Width="2.4375" Height="0.01" />
    <TextItem X="0.0312" Y="3.4375" Width="1.8438" Height="0.1562" Text="Vitamin_x0020_D_x0020_0mcg" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="3.4375" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="3.7762" Width="2.4375" Height="0.01" />
    <TextItem X="0.0312" Y="3.625" Width="1.8438" Height="0.1562" Text="Calcium_x0020_0mg" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="3.625" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="3.9638" Width="2.4375" Height="0.01" />
    <TextItem X="0.0312" Y="3.8125" Width="1.8438" Height="0.1562" Text="Iron_x0020_0mg" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="3.8125" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,Point,,,False,90,,CP850" TextAlignment="Right" />
    <LineShapeItem X="0.0312" Y="4.1512" Width="2.4375" Height="0.042" StrokeThickness="0.042" />
    <TextItem X="0.0312" Y="4" Width="1.8438" Height="0.1562" Text="Potassium_x0020_0mg" Font="Arial,8,Point,,,False,90,,CP850" />
    <TextItem X="1.875" Y="4" Width="0.5938" Height="0.1562" Text="_x0030_0_x0025_" Font="Arial,8,Point,,,False,90,,CP850" TextAlignment="Right" />
    <TextItem X="0.0938" Y="4.2188" Width="2.375" Height="0.3125" Text="The_x0020__x0025__x0020_Daily_x0020_Value_x0020__x0028_DV_x0029__x0020_tells_x0020_you_x0020_how_x0020_much_x0020_a_x0020_nutriend_x0020_in_x0020_a_x0020_serving_x0020_of_x0020_food_x0020_contributes_x0020_to_x0020_a_x0020_daily_x0020_diet._x0020_2_x002C_000_x0020_calories_x0020_a_x0020_day_x0020_is_x0020_used_x0020_for_x0020_general_x0020_nutrition_x0020_advice." Font="Arial,6,Point,,,False,90,,CP850" />
    <TextItem X="0.0312" Y="4.2188" Width="0.0625" Height="0.0938" Text="_x002A_" Font="Arial,6,Point,,,False,90,,CP850" />
  </Items>
</ThermalLabel>